Instance: mii-qst-pro-eortc-qlq-c30
InstanceOf: mii-pr-pro-questionnaire
Title: "MII QST PRO EORTC QLQ-C30"
Description: "EORTC QLQ-C30 Quality of Life Questionnaire - Core 30 for cancer patients"
Usage: #definition

* url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-eortc-qlq-c30"
* status = #active
* experimental = true
* language = #en
* version = "0.1.0"
* title = "EORTC QLQ-C30 Quality of Life Questionnaire"
* code[snomed] = $SCT#273446001 "European Organisation for Research and Treatment of Cancer - Quality of Life questionnaire (assessment scale)"
* code[mii] = http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-questionnaire-catalogue#eortc-qlq-c30 "EORTC QLQ-C30 Quality of Life Questionnaire"

* extension[capabilities].extension[displayable].valueBoolean = true
* extension[capabilities].extension[collectable].valueBoolean = true
* extension[capabilities].extension[calculatable].valueBoolean = true
* extension[capabilities].extension[extractable].valueBoolean = true
* extension[capabilities].extension[domainAligned].valueBoolean = true

// Introduction text
* item[0].linkId = "QLQ-C30.Introduction"
* item[0].type = #display
* item[0].text = "We are interested in some things about you and your health. Please answer all of the questions yourself by circling the number that best applies to you. There are no 'right' or 'wrong' answers. The information that you provide will remain strictly confidential."
* item[0].text.extension[0].url = $hl7-translation
* item[0].text.extension[0].extension[0].url = "lang"
* item[0].text.extension[0].extension[0].valueCode = #de
* item[0].text.extension[0].extension[1].url = "content"
* item[0].text.extension[0].extension[1].valueString = "Wir möchten gerne einiges über Sie und Ihre Gesundheit erfahren. Bitte beantworten Sie alle Fragen, indem Sie die Zahl ankreuzen, die am besten auf Sie zutrifft. Es gibt keine 'richtigen' oder 'falschen' Antworten. Alle Ihre Angaben werden streng vertraulich behandelt."

// Section 1: Physical functioning items
* item[1].linkId = "qlq-c30-q01"
* item[1].type = #choice
* item[1].prefix = "1"
* item[1].text = "Do you have any trouble doing strenuous activities, like carrying a heavy shopping bag or a suitcase?"
* item[1].text.extension[0].url = $hl7-translation
* item[1].text.extension[0].extension[0].url = "lang"
* item[1].text.extension[0].extension[0].valueCode = #de
* item[1].text.extension[0].extension[1].url = "content"
* item[1].text.extension[0].extension[1].valueString = "Bereitet es Ihnen Schwierigkeiten, sich körperlich anzustrengen (z.B. eine schwere Einkaufstasche oder einen Koffer zu tragen)?"
* item[1].answerOption[0].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[1].answerOption[0].valueCoding.code = #not-at-all
* item[1].answerOption[0].valueCoding.display = "Not at all"
* item[1].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Überhaupt nicht"
* item[1].answerOption[0].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[1].answerOption[0].extension.valueDecimal = 1
* item[1].answerOption[1].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[1].answerOption[1].valueCoding.code = #a-little
* item[1].answerOption[1].valueCoding.display = "A little"
* item[1].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Wenig"
* item[1].answerOption[1].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[1].answerOption[1].extension.valueDecimal = 2
* item[1].answerOption[2].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[1].answerOption[2].valueCoding.code = #quite-a-bit
* item[1].answerOption[2].valueCoding.display = "Quite a bit"
* item[1].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Mäßig"
* item[1].answerOption[2].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[1].answerOption[2].extension.valueDecimal = 3
* item[1].answerOption[3].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[1].answerOption[3].valueCoding.code = #very-much
* item[1].answerOption[3].valueCoding.display = "Very much"
* item[1].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Sehr"
* item[1].answerOption[3].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[1].answerOption[3].extension.valueDecimal = 4

* item[2].linkId = "qlq-c30-q02"
* item[2].type = #choice
* item[2].prefix = "2"
* item[2].text = "Do you have any trouble taking a long walk?"
* item[2].text.extension[0].url = $hl7-translation
* item[2].text.extension[0].extension[0].url = "lang"
* item[2].text.extension[0].extension[0].valueCode = #de
* item[2].text.extension[0].extension[1].url = "content"
* item[2].text.extension[0].extension[1].valueString = "Bereitet es Ihnen Schwierigkeiten, einen längeren Spaziergang zu machen?"
* item[2].answerOption[0].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[2].answerOption[0].valueCoding.code = #not-at-all
* item[2].answerOption[0].valueCoding.display = "Not at all"
* item[2].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Überhaupt nicht"
* item[2].answerOption[0].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[2].answerOption[0].extension.valueDecimal = 1
* item[2].answerOption[1].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[2].answerOption[1].valueCoding.code = #a-little
* item[2].answerOption[1].valueCoding.display = "A little"
* item[2].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Wenig"
* item[2].answerOption[1].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[2].answerOption[1].extension.valueDecimal = 2
* item[2].answerOption[2].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[2].answerOption[2].valueCoding.code = #quite-a-bit
* item[2].answerOption[2].valueCoding.display = "Quite a bit"
* item[2].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Mäßig"
* item[2].answerOption[2].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[2].answerOption[2].extension.valueDecimal = 3
* item[2].answerOption[3].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[2].answerOption[3].valueCoding.code = #very-much
* item[2].answerOption[3].valueCoding.display = "Very much"
* item[2].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Sehr"
* item[2].answerOption[3].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[2].answerOption[3].extension.valueDecimal = 4

* item[3].linkId = "qlq-c30-q03"
* item[3].type = #choice
* item[3].prefix = "3"
* item[3].text = "Do you have any trouble taking a short walk outside of the house?"
* item[3].text.extension[0].url = $hl7-translation
* item[3].text.extension[0].extension[0].url = "lang"
* item[3].text.extension[0].extension[0].valueCode = #de
* item[3].text.extension[0].extension[1].url = "content"
* item[3].text.extension[0].extension[1].valueString = "Bereitet es Ihnen Schwierigkeiten, eine kurze Strecke außerhalb des Hauses zu gehen?"
* item[3].answerOption[0].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[3].answerOption[0].valueCoding.code = #not-at-all
* item[3].answerOption[0].valueCoding.display = "Not at all"
* item[3].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Überhaupt nicht"
* item[3].answerOption[0].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[3].answerOption[0].extension.valueDecimal = 1
* item[3].answerOption[1].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[3].answerOption[1].valueCoding.code = #a-little
* item[3].answerOption[1].valueCoding.display = "A little"
* item[3].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Wenig"
* item[3].answerOption[1].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[3].answerOption[1].extension.valueDecimal = 2
* item[3].answerOption[2].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[3].answerOption[2].valueCoding.code = #quite-a-bit
* item[3].answerOption[2].valueCoding.display = "Quite a bit"
* item[3].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Mäßig"
* item[3].answerOption[2].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[3].answerOption[2].extension.valueDecimal = 3
* item[3].answerOption[3].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[3].answerOption[3].valueCoding.code = #very-much
* item[3].answerOption[3].valueCoding.display = "Very much"
* item[3].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Sehr"
* item[3].answerOption[3].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[3].answerOption[3].extension.valueDecimal = 4

* item[4].linkId = "qlq-c30-q04"
* item[4].type = #choice
* item[4].prefix = "4"
* item[4].text = "Do you need to stay in bed or a chair during the day?"
* item[4].text.extension[0].url = $hl7-translation
* item[4].text.extension[0].extension[0].url = "lang"
* item[4].text.extension[0].extension[0].valueCode = #de
* item[4].text.extension[0].extension[1].url = "content"
* item[4].text.extension[0].extension[1].valueString = "Müssen Sie tagsüber im Bett liegen oder in einem Sessel sitzen?"
* item[4].answerOption[0].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[4].answerOption[0].valueCoding.code = #not-at-all
* item[4].answerOption[0].valueCoding.display = "Not at all"
* item[4].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Überhaupt nicht"
* item[4].answerOption[0].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[4].answerOption[0].extension.valueDecimal = 1
* item[4].answerOption[1].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[4].answerOption[1].valueCoding.code = #a-little
* item[4].answerOption[1].valueCoding.display = "A little"
* item[4].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Wenig"
* item[4].answerOption[1].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[4].answerOption[1].extension.valueDecimal = 2
* item[4].answerOption[2].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[4].answerOption[2].valueCoding.code = #quite-a-bit
* item[4].answerOption[2].valueCoding.display = "Quite a bit"
* item[4].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Mäßig"
* item[4].answerOption[2].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[4].answerOption[2].extension.valueDecimal = 3
* item[4].answerOption[3].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[4].answerOption[3].valueCoding.code = #very-much
* item[4].answerOption[3].valueCoding.display = "Very much"
* item[4].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Sehr"
* item[4].answerOption[3].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[4].answerOption[3].extension.valueDecimal = 4

* item[5].linkId = "qlq-c30-q05"
* item[5].type = #choice
* item[5].prefix = "5"
* item[5].text = "Do you need help with eating, dressing, washing yourself or using the toilet?"
* item[5].text.extension[0].url = $hl7-translation
* item[5].text.extension[0].extension[0].url = "lang"
* item[5].text.extension[0].extension[0].valueCode = #de
* item[5].text.extension[0].extension[1].url = "content"
* item[5].text.extension[0].extension[1].valueString = "Brauchen Sie Hilfe beim Essen, Anziehen, Waschen oder Benutzen der Toilette?"
* item[5].answerOption[0].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[5].answerOption[0].valueCoding.code = #not-at-all
* item[5].answerOption[0].valueCoding.display = "Not at all"
* item[5].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Überhaupt nicht"
* item[5].answerOption[0].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[5].answerOption[0].extension.valueDecimal = 1
* item[5].answerOption[1].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[5].answerOption[1].valueCoding.code = #a-little
* item[5].answerOption[1].valueCoding.display = "A little"
* item[5].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Wenig"
* item[5].answerOption[1].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[5].answerOption[1].extension.valueDecimal = 2
* item[5].answerOption[2].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[5].answerOption[2].valueCoding.code = #quite-a-bit
* item[5].answerOption[2].valueCoding.display = "Quite a bit"
* item[5].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Mäßig"
* item[5].answerOption[2].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[5].answerOption[2].extension.valueDecimal = 3
* item[5].answerOption[3].valueCoding.system = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-eortc-qlq-c30"
* item[5].answerOption[3].valueCoding.code = #very-much
* item[5].answerOption[3].valueCoding.display = "Very much"
* item[5].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Sehr"
* item[5].answerOption[3].extension.url = "http://hl7.org/fhir/StructureDefinition/itemWeight"
* item[5].answerOption[3].extension.valueDecimal = 4