Instance: mii-qst-pro-dass-dass21
InstanceOf: mii-pr-pro-questionnaire
Title: "MII QST PRO DASS-21"
Description: "Depression Anxiety Stress Scales - 21 Items (DASS-21)"
Usage: #definition
* insert Version
* insert MetaProfile(https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire)

* url = $mii-qst-pro-dass-dass21
* status = #active
* experimental = true
* language = #en
* code[+] = $mii-cs-pro-questionnaire-catalogue#dass-dass21 "DASS-21 (Depression Anxiety Stress Scales - 21 Items)"

* extension[capabilities].extension[displayable].valueBoolean = true
* extension[capabilities].extension[collectable].valueBoolean = true
* extension[capabilities].extension[calculatable].valueBoolean = true
* extension[capabilities].extension[extractable].valueBoolean = true
* extension[capabilities].extension[domainAligned].valueBoolean = true

// FHIR Variables for subscale score calculations
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/variable"
* extension[=].valueExpression.name = "depressionRaw"
* extension[=].valueExpression.language = #text/fhirpath
* extension[=].valueExpression.expression = "%resource.item.where(linkId.matches('^dass-dass21-q(03|05|10|13|16|17|21)$')).answer.value.ordinal().sum()"

* extension[+].url = "http://hl7.org/fhir/StructureDefinition/variable"
* extension[=].valueExpression.name = "anxietyRaw"
* extension[=].valueExpression.language = #text/fhirpath
* extension[=].valueExpression.expression = "%resource.item.where(linkId.matches('^dass-dass21-q(02|04|07|09|15|19|20)$')).answer.value.ordinal().sum()"

* extension[+].url = "http://hl7.org/fhir/StructureDefinition/variable"
* extension[=].valueExpression.name = "stressRaw"
* extension[=].valueExpression.language = #text/fhirpath
* extension[=].valueExpression.expression = "%resource.item.where(linkId.matches('^dass-dass21-q(01|06|08|11|12|14|18)$')).answer.value.ordinal().sum()"

// ============================================================================
// Display item: Instructions
// ============================================================================

* item[0].linkId = "DASS-21.Description"
* item[0].type = #display
* item[0].text = "Please read each statement and select a number 0, 1, 2 or 3 which indicates how much the statement applied to you over the past week."
* item[0].text.extension[0].url = $hl7-translation
* item[0].text.extension[0].extension[0].url = "lang"
* item[0].text.extension[0].extension[0].valueCode = #de
* item[0].text.extension[0].extension[1].url = "content"
* item[0].text.extension[0].extension[1].valueString = "Bitte lesen Sie jede Aussage und wählen Sie eine Zahl 0, 1, 2 oder 3, die angibt, wie sehr die Aussage während der letzten Woche auf Sie zutraf."

// ============================================================================
// Question items 1-21
// ============================================================================

// Q1 - Stress: I found it hard to wind down
* item[1].linkId = "dass-dass21-q01"
* item[1].type = #choice
* item[1].prefix = "1"
* item[1].code = $mii-cs-pro-dass-21#dass-dass21-q01
* item[1].text = "I found it hard to wind down"
* item[1].text.extension[0].url = $hl7-translation
* item[1].text.extension[0].extension[0].url = "lang"
* item[1].text.extension[0].extension[0].valueCode = #de
* item[1].text.extension[0].extension[1].url = "content"
* item[1].text.extension[0].extension[1].valueString = "Ich fand es schwer abzuschalten"
* item[1].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[1].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[1].answerOption[0].extension.url = $hl7-ordinal-value
* item[1].answerOption[0].extension.valueDecimal = 0
* item[1].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[1].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[1].answerOption[1].extension.url = $hl7-ordinal-value
* item[1].answerOption[1].extension.valueDecimal = 1
* item[1].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[1].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[1].answerOption[2].extension.url = $hl7-ordinal-value
* item[1].answerOption[2].extension.valueDecimal = 2
* item[1].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[1].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[1].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[1].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[1].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[1].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[1].answerOption[3].extension.url = $hl7-ordinal-value
* item[1].answerOption[3].extension.valueDecimal = 3

// Q2 - Anxiety: I was aware of dryness of my mouth
* item[2].linkId = "dass-dass21-q02"
* item[2].type = #choice
* item[2].prefix = "2"
* item[2].code = $mii-cs-pro-dass-21#dass-dass21-q02
* item[2].text = "I was aware of dryness of my mouth"
* item[2].text.extension[0].url = $hl7-translation
* item[2].text.extension[0].extension[0].url = "lang"
* item[2].text.extension[0].extension[0].valueCode = #de
* item[2].text.extension[0].extension[1].url = "content"
* item[2].text.extension[0].extension[1].valueString = "Ich bemerkte Mundtrockenheit"
* item[2].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[2].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[2].answerOption[0].extension.url = $hl7-ordinal-value
* item[2].answerOption[0].extension.valueDecimal = 0
* item[2].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[2].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[2].answerOption[1].extension.url = $hl7-ordinal-value
* item[2].answerOption[1].extension.valueDecimal = 1
* item[2].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[2].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[2].answerOption[2].extension.url = $hl7-ordinal-value
* item[2].answerOption[2].extension.valueDecimal = 2
* item[2].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[2].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[2].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[2].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[2].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[2].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[2].answerOption[3].extension.url = $hl7-ordinal-value
* item[2].answerOption[3].extension.valueDecimal = 3

// Q3 - Depression: I couldn't seem to experience any positive feeling at all
* item[3].linkId = "dass-dass21-q03"
* item[3].type = #choice
* item[3].prefix = "3"
* item[3].code = $mii-cs-pro-dass-21#dass-dass21-q03
* item[3].text = "I couldn't seem to experience any positive feeling at all"
* item[3].text.extension[0].url = $hl7-translation
* item[3].text.extension[0].extension[0].url = "lang"
* item[3].text.extension[0].extension[0].valueCode = #de
* item[3].text.extension[0].extension[1].url = "content"
* item[3].text.extension[0].extension[1].valueString = "Ich konnte überhaupt keine positiven Gefühle mehr erleben"
* item[3].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[3].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[3].answerOption[0].extension.url = $hl7-ordinal-value
* item[3].answerOption[0].extension.valueDecimal = 0
* item[3].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[3].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[3].answerOption[1].extension.url = $hl7-ordinal-value
* item[3].answerOption[1].extension.valueDecimal = 1
* item[3].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[3].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[3].answerOption[2].extension.url = $hl7-ordinal-value
* item[3].answerOption[2].extension.valueDecimal = 2
* item[3].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[3].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[3].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[3].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[3].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[3].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[3].answerOption[3].extension.url = $hl7-ordinal-value
* item[3].answerOption[3].extension.valueDecimal = 3

// Q4 - Anxiety: I experienced breathing difficulty
* item[4].linkId = "dass-dass21-q04"
* item[4].type = #choice
* item[4].prefix = "4"
* item[4].code = $mii-cs-pro-dass-21#dass-dass21-q04
* item[4].text = "I experienced breathing difficulty"
* item[4].text.extension[0].url = $hl7-translation
* item[4].text.extension[0].extension[0].url = "lang"
* item[4].text.extension[0].extension[0].valueCode = #de
* item[4].text.extension[0].extension[1].url = "content"
* item[4].text.extension[0].extension[1].valueString = "Ich hatte Atemschwierigkeiten"
* item[4].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[4].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[4].answerOption[0].extension.url = $hl7-ordinal-value
* item[4].answerOption[0].extension.valueDecimal = 0
* item[4].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[4].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[4].answerOption[1].extension.url = $hl7-ordinal-value
* item[4].answerOption[1].extension.valueDecimal = 1
* item[4].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[4].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[4].answerOption[2].extension.url = $hl7-ordinal-value
* item[4].answerOption[2].extension.valueDecimal = 2
* item[4].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[4].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[4].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[4].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[4].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[4].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[4].answerOption[3].extension.url = $hl7-ordinal-value
* item[4].answerOption[3].extension.valueDecimal = 3

// Q5 - Depression: I found it difficult to work up the initiative to do things
* item[5].linkId = "dass-dass21-q05"
* item[5].type = #choice
* item[5].prefix = "5"
* item[5].code = $mii-cs-pro-dass-21#dass-dass21-q05
* item[5].text = "I found it difficult to work up the initiative to do things"
* item[5].text.extension[0].url = $hl7-translation
* item[5].text.extension[0].extension[0].url = "lang"
* item[5].text.extension[0].extension[0].valueCode = #de
* item[5].text.extension[0].extension[1].url = "content"
* item[5].text.extension[0].extension[1].valueString = "Ich fand es schwierig, die Initiative zum Tun aufzubringen"
* item[5].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[5].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[5].answerOption[0].extension.url = $hl7-ordinal-value
* item[5].answerOption[0].extension.valueDecimal = 0
* item[5].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[5].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[5].answerOption[1].extension.url = $hl7-ordinal-value
* item[5].answerOption[1].extension.valueDecimal = 1
* item[5].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[5].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[5].answerOption[2].extension.url = $hl7-ordinal-value
* item[5].answerOption[2].extension.valueDecimal = 2
* item[5].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[5].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[5].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[5].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[5].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[5].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[5].answerOption[3].extension.url = $hl7-ordinal-value
* item[5].answerOption[3].extension.valueDecimal = 3

// Q6 - Stress: I tended to over-react to situations
* item[6].linkId = "dass-dass21-q06"
* item[6].type = #choice
* item[6].prefix = "6"
* item[6].code = $mii-cs-pro-dass-21#dass-dass21-q06
* item[6].text = "I tended to over-react to situations"
* item[6].text.extension[0].url = $hl7-translation
* item[6].text.extension[0].extension[0].url = "lang"
* item[6].text.extension[0].extension[0].valueCode = #de
* item[6].text.extension[0].extension[1].url = "content"
* item[6].text.extension[0].extension[1].valueString = "Ich neigte dazu, auf Situationen überzureagieren"
* item[6].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[6].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[6].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[6].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[6].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[6].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[6].answerOption[0].extension.url = $hl7-ordinal-value
* item[6].answerOption[0].extension.valueDecimal = 0
* item[6].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[6].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[6].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[6].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[6].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[6].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[6].answerOption[1].extension.url = $hl7-ordinal-value
* item[6].answerOption[1].extension.valueDecimal = 1
* item[6].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[6].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[6].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[6].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[6].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[6].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[6].answerOption[2].extension.url = $hl7-ordinal-value
* item[6].answerOption[2].extension.valueDecimal = 2
* item[6].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[6].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[6].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[6].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[6].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[6].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[6].answerOption[3].extension.url = $hl7-ordinal-value
* item[6].answerOption[3].extension.valueDecimal = 3

// Q7 - Anxiety: I experienced trembling (e.g., in the hands)
* item[7].linkId = "dass-dass21-q07"
* item[7].type = #choice
* item[7].prefix = "7"
* item[7].code = $mii-cs-pro-dass-21#dass-dass21-q07
* item[7].text = "I experienced trembling (e.g., in the hands)"
* item[7].text.extension[0].url = $hl7-translation
* item[7].text.extension[0].extension[0].url = "lang"
* item[7].text.extension[0].extension[0].valueCode = #de
* item[7].text.extension[0].extension[1].url = "content"
* item[7].text.extension[0].extension[1].valueString = "Ich zitterte (z.B. an den Händen)"
* item[7].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[7].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[7].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[7].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[7].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[7].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[7].answerOption[0].extension.url = $hl7-ordinal-value
* item[7].answerOption[0].extension.valueDecimal = 0
* item[7].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[7].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[7].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[7].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[7].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[7].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[7].answerOption[1].extension.url = $hl7-ordinal-value
* item[7].answerOption[1].extension.valueDecimal = 1
* item[7].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[7].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[7].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[7].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[7].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[7].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[7].answerOption[2].extension.url = $hl7-ordinal-value
* item[7].answerOption[2].extension.valueDecimal = 2
* item[7].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[7].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[7].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[7].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[7].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[7].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[7].answerOption[3].extension.url = $hl7-ordinal-value
* item[7].answerOption[3].extension.valueDecimal = 3

// Q8 - Stress: I felt that I was using a lot of nervous energy
* item[8].linkId = "dass-dass21-q08"
* item[8].type = #choice
* item[8].prefix = "8"
* item[8].code = $mii-cs-pro-dass-21#dass-dass21-q08
* item[8].text = "I felt that I was using a lot of nervous energy"
* item[8].text.extension[0].url = $hl7-translation
* item[8].text.extension[0].extension[0].url = "lang"
* item[8].text.extension[0].extension[0].valueCode = #de
* item[8].text.extension[0].extension[1].url = "content"
* item[8].text.extension[0].extension[1].valueString = "Ich merkte, dass ich viel nervöse Energie verbrauchte"
* item[8].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[8].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[8].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[8].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[8].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[8].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[8].answerOption[0].extension.url = $hl7-ordinal-value
* item[8].answerOption[0].extension.valueDecimal = 0
* item[8].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[8].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[8].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[8].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[8].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[8].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[8].answerOption[1].extension.url = $hl7-ordinal-value
* item[8].answerOption[1].extension.valueDecimal = 1
* item[8].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[8].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[8].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[8].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[8].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[8].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[8].answerOption[2].extension.url = $hl7-ordinal-value
* item[8].answerOption[2].extension.valueDecimal = 2
* item[8].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[8].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[8].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[8].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[8].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[8].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[8].answerOption[3].extension.url = $hl7-ordinal-value
* item[8].answerOption[3].extension.valueDecimal = 3

// Q9 - Anxiety: I was worried about situations in which I might panic and make a fool of myself
* item[9].linkId = "dass-dass21-q09"
* item[9].type = #choice
* item[9].prefix = "9"
* item[9].code = $mii-cs-pro-dass-21#dass-dass21-q09
* item[9].text = "I was worried about situations in which I might panic and make a fool of myself"
* item[9].text.extension[0].url = $hl7-translation
* item[9].text.extension[0].extension[0].url = "lang"
* item[9].text.extension[0].extension[0].valueCode = #de
* item[9].text.extension[0].extension[1].url = "content"
* item[9].text.extension[0].extension[1].valueString = "Ich machte mir Sorgen über Situationen, in denen ich in Panik geraten könnte"
* item[9].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[9].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[9].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[9].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[9].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[9].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[9].answerOption[0].extension.url = $hl7-ordinal-value
* item[9].answerOption[0].extension.valueDecimal = 0
* item[9].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[9].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[9].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[9].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[9].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[9].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[9].answerOption[1].extension.url = $hl7-ordinal-value
* item[9].answerOption[1].extension.valueDecimal = 1
* item[9].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[9].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[9].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[9].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[9].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[9].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[9].answerOption[2].extension.url = $hl7-ordinal-value
* item[9].answerOption[2].extension.valueDecimal = 2
* item[9].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[9].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[9].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[9].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[9].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[9].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[9].answerOption[3].extension.url = $hl7-ordinal-value
* item[9].answerOption[3].extension.valueDecimal = 3

// Q10 - Depression: I felt that I had nothing to look forward to
* item[10].linkId = "dass-dass21-q10"
* item[10].type = #choice
* item[10].prefix = "10"
* item[10].code = $mii-cs-pro-dass-21#dass-dass21-q10
* item[10].text = "I felt that I had nothing to look forward to"
* item[10].text.extension[0].url = $hl7-translation
* item[10].text.extension[0].extension[0].url = "lang"
* item[10].text.extension[0].extension[0].valueCode = #de
* item[10].text.extension[0].extension[1].url = "content"
* item[10].text.extension[0].extension[1].valueString = "Ich hatte das Gefühl, dass ich nichts erwarten konnte"
* item[10].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[10].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[10].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[10].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[10].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[10].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[10].answerOption[0].extension.url = $hl7-ordinal-value
* item[10].answerOption[0].extension.valueDecimal = 0
* item[10].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[10].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[10].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[10].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[10].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[10].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[10].answerOption[1].extension.url = $hl7-ordinal-value
* item[10].answerOption[1].extension.valueDecimal = 1
* item[10].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[10].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[10].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[10].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[10].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[10].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[10].answerOption[2].extension.url = $hl7-ordinal-value
* item[10].answerOption[2].extension.valueDecimal = 2
* item[10].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[10].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[10].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[10].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[10].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[10].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[10].answerOption[3].extension.url = $hl7-ordinal-value
* item[10].answerOption[3].extension.valueDecimal = 3

// Q11 - Stress: I found myself getting agitated
* item[11].linkId = "dass-dass21-q11"
* item[11].type = #choice
* item[11].prefix = "11"
* item[11].code = $mii-cs-pro-dass-21#dass-dass21-q11
* item[11].text = "I found myself getting agitated"
* item[11].text.extension[0].url = $hl7-translation
* item[11].text.extension[0].extension[0].url = "lang"
* item[11].text.extension[0].extension[0].valueCode = #de
* item[11].text.extension[0].extension[1].url = "content"
* item[11].text.extension[0].extension[1].valueString = "Ich merkte, dass ich unruhig wurde"
* item[11].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[11].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[11].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[11].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[11].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[11].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[11].answerOption[0].extension.url = $hl7-ordinal-value
* item[11].answerOption[0].extension.valueDecimal = 0
* item[11].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[11].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[11].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[11].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[11].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[11].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[11].answerOption[1].extension.url = $hl7-ordinal-value
* item[11].answerOption[1].extension.valueDecimal = 1
* item[11].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[11].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[11].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[11].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[11].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[11].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[11].answerOption[2].extension.url = $hl7-ordinal-value
* item[11].answerOption[2].extension.valueDecimal = 2
* item[11].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[11].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[11].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[11].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[11].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[11].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[11].answerOption[3].extension.url = $hl7-ordinal-value
* item[11].answerOption[3].extension.valueDecimal = 3

// Q12 - Stress: I found it difficult to relax
* item[12].linkId = "dass-dass21-q12"
* item[12].type = #choice
* item[12].prefix = "12"
* item[12].code = $mii-cs-pro-dass-21#dass-dass21-q12
* item[12].text = "I found it difficult to relax"
* item[12].text.extension[0].url = $hl7-translation
* item[12].text.extension[0].extension[0].url = "lang"
* item[12].text.extension[0].extension[0].valueCode = #de
* item[12].text.extension[0].extension[1].url = "content"
* item[12].text.extension[0].extension[1].valueString = "Ich fand es schwierig, mich zu entspannen"
* item[12].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[12].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[12].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[12].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[12].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[12].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[12].answerOption[0].extension.url = $hl7-ordinal-value
* item[12].answerOption[0].extension.valueDecimal = 0
* item[12].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[12].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[12].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[12].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[12].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[12].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[12].answerOption[1].extension.url = $hl7-ordinal-value
* item[12].answerOption[1].extension.valueDecimal = 1
* item[12].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[12].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[12].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[12].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[12].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[12].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[12].answerOption[2].extension.url = $hl7-ordinal-value
* item[12].answerOption[2].extension.valueDecimal = 2
* item[12].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[12].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[12].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[12].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[12].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[12].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[12].answerOption[3].extension.url = $hl7-ordinal-value
* item[12].answerOption[3].extension.valueDecimal = 3

// Q13 - Depression: I felt down-hearted and blue
* item[13].linkId = "dass-dass21-q13"
* item[13].type = #choice
* item[13].prefix = "13"
* item[13].code = $mii-cs-pro-dass-21#dass-dass21-q13
* item[13].text = "I felt down-hearted and blue"
* item[13].text.extension[0].url = $hl7-translation
* item[13].text.extension[0].extension[0].url = "lang"
* item[13].text.extension[0].extension[0].valueCode = #de
* item[13].text.extension[0].extension[1].url = "content"
* item[13].text.extension[0].extension[1].valueString = "Ich fühlte mich niedergeschlagen und traurig"
* item[13].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[13].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[13].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[13].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[13].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[13].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[13].answerOption[0].extension.url = $hl7-ordinal-value
* item[13].answerOption[0].extension.valueDecimal = 0
* item[13].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[13].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[13].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[13].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[13].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[13].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[13].answerOption[1].extension.url = $hl7-ordinal-value
* item[13].answerOption[1].extension.valueDecimal = 1
* item[13].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[13].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[13].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[13].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[13].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[13].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[13].answerOption[2].extension.url = $hl7-ordinal-value
* item[13].answerOption[2].extension.valueDecimal = 2
* item[13].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[13].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[13].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[13].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[13].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[13].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[13].answerOption[3].extension.url = $hl7-ordinal-value
* item[13].answerOption[3].extension.valueDecimal = 3

// Q14 - Stress: I was intolerant of anything that kept me from getting on with what I was doing
* item[14].linkId = "dass-dass21-q14"
* item[14].type = #choice
* item[14].prefix = "14"
* item[14].code = $mii-cs-pro-dass-21#dass-dass21-q14
* item[14].text = "I was intolerant of anything that kept me from getting on with what I was doing"
* item[14].text.extension[0].url = $hl7-translation
* item[14].text.extension[0].extension[0].url = "lang"
* item[14].text.extension[0].extension[0].valueCode = #de
* item[14].text.extension[0].extension[1].url = "content"
* item[14].text.extension[0].extension[1].valueString = "Ich war ungeduldig, wenn ich aufgehalten wurde"
* item[14].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[14].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[14].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[14].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[14].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[14].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[14].answerOption[0].extension.url = $hl7-ordinal-value
* item[14].answerOption[0].extension.valueDecimal = 0
* item[14].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[14].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[14].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[14].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[14].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[14].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[14].answerOption[1].extension.url = $hl7-ordinal-value
* item[14].answerOption[1].extension.valueDecimal = 1
* item[14].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[14].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[14].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[14].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[14].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[14].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[14].answerOption[2].extension.url = $hl7-ordinal-value
* item[14].answerOption[2].extension.valueDecimal = 2
* item[14].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[14].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[14].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[14].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[14].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[14].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[14].answerOption[3].extension.url = $hl7-ordinal-value
* item[14].answerOption[3].extension.valueDecimal = 3

// Q15 - Anxiety: I felt I was close to panic
* item[15].linkId = "dass-dass21-q15"
* item[15].type = #choice
* item[15].prefix = "15"
* item[15].code = $mii-cs-pro-dass-21#dass-dass21-q15
* item[15].text = "I felt I was close to panic"
* item[15].text.extension[0].url = $hl7-translation
* item[15].text.extension[0].extension[0].url = "lang"
* item[15].text.extension[0].extension[0].valueCode = #de
* item[15].text.extension[0].extension[1].url = "content"
* item[15].text.extension[0].extension[1].valueString = "Ich fühlte mich einer Panik nahe"
* item[15].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[15].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[15].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[15].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[15].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[15].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[15].answerOption[0].extension.url = $hl7-ordinal-value
* item[15].answerOption[0].extension.valueDecimal = 0
* item[15].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[15].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[15].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[15].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[15].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[15].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[15].answerOption[1].extension.url = $hl7-ordinal-value
* item[15].answerOption[1].extension.valueDecimal = 1
* item[15].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[15].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[15].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[15].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[15].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[15].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[15].answerOption[2].extension.url = $hl7-ordinal-value
* item[15].answerOption[2].extension.valueDecimal = 2
* item[15].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[15].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[15].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[15].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[15].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[15].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[15].answerOption[3].extension.url = $hl7-ordinal-value
* item[15].answerOption[3].extension.valueDecimal = 3

// Q16 - Depression: I was unable to become enthusiastic about anything
* item[16].linkId = "dass-dass21-q16"
* item[16].type = #choice
* item[16].prefix = "16"
* item[16].code = $mii-cs-pro-dass-21#dass-dass21-q16
* item[16].text = "I was unable to become enthusiastic about anything"
* item[16].text.extension[0].url = $hl7-translation
* item[16].text.extension[0].extension[0].url = "lang"
* item[16].text.extension[0].extension[0].valueCode = #de
* item[16].text.extension[0].extension[1].url = "content"
* item[16].text.extension[0].extension[1].valueString = "Ich konnte mich für nichts begeistern"
* item[16].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[16].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[16].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[16].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[16].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[16].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[16].answerOption[0].extension.url = $hl7-ordinal-value
* item[16].answerOption[0].extension.valueDecimal = 0
* item[16].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[16].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[16].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[16].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[16].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[16].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[16].answerOption[1].extension.url = $hl7-ordinal-value
* item[16].answerOption[1].extension.valueDecimal = 1
* item[16].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[16].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[16].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[16].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[16].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[16].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[16].answerOption[2].extension.url = $hl7-ordinal-value
* item[16].answerOption[2].extension.valueDecimal = 2
* item[16].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[16].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[16].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[16].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[16].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[16].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[16].answerOption[3].extension.url = $hl7-ordinal-value
* item[16].answerOption[3].extension.valueDecimal = 3

// Q17 - Depression: I felt I wasn't worth much as a person
* item[17].linkId = "dass-dass21-q17"
* item[17].type = #choice
* item[17].prefix = "17"
* item[17].code = $mii-cs-pro-dass-21#dass-dass21-q17
* item[17].text = "I felt I wasn't worth much as a person"
* item[17].text.extension[0].url = $hl7-translation
* item[17].text.extension[0].extension[0].url = "lang"
* item[17].text.extension[0].extension[0].valueCode = #de
* item[17].text.extension[0].extension[1].url = "content"
* item[17].text.extension[0].extension[1].valueString = "Ich hatte das Gefühl, nicht viel wert zu sein"
* item[17].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[17].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[17].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[17].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[17].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[17].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[17].answerOption[0].extension.url = $hl7-ordinal-value
* item[17].answerOption[0].extension.valueDecimal = 0
* item[17].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[17].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[17].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[17].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[17].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[17].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[17].answerOption[1].extension.url = $hl7-ordinal-value
* item[17].answerOption[1].extension.valueDecimal = 1
* item[17].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[17].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[17].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[17].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[17].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[17].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[17].answerOption[2].extension.url = $hl7-ordinal-value
* item[17].answerOption[2].extension.valueDecimal = 2
* item[17].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[17].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[17].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[17].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[17].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[17].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[17].answerOption[3].extension.url = $hl7-ordinal-value
* item[17].answerOption[3].extension.valueDecimal = 3

// Q18 - Stress: I felt that I was rather touchy
* item[18].linkId = "dass-dass21-q18"
* item[18].type = #choice
* item[18].prefix = "18"
* item[18].code = $mii-cs-pro-dass-21#dass-dass21-q18
* item[18].text = "I felt that I was rather touchy"
* item[18].text.extension[0].url = $hl7-translation
* item[18].text.extension[0].extension[0].url = "lang"
* item[18].text.extension[0].extension[0].valueCode = #de
* item[18].text.extension[0].extension[1].url = "content"
* item[18].text.extension[0].extension[1].valueString = "Ich merkte, dass ich ziemlich empfindlich war"
* item[18].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[18].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[18].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[18].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[18].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[18].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[18].answerOption[0].extension.url = $hl7-ordinal-value
* item[18].answerOption[0].extension.valueDecimal = 0
* item[18].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[18].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[18].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[18].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[18].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[18].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[18].answerOption[1].extension.url = $hl7-ordinal-value
* item[18].answerOption[1].extension.valueDecimal = 1
* item[18].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[18].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[18].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[18].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[18].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[18].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[18].answerOption[2].extension.url = $hl7-ordinal-value
* item[18].answerOption[2].extension.valueDecimal = 2
* item[18].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[18].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[18].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[18].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[18].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[18].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[18].answerOption[3].extension.url = $hl7-ordinal-value
* item[18].answerOption[3].extension.valueDecimal = 3

// Q19 - Anxiety: I was aware of the action of my heart in the absence of physical exertion
* item[19].linkId = "dass-dass21-q19"
* item[19].type = #choice
* item[19].prefix = "19"
* item[19].code = $mii-cs-pro-dass-21#dass-dass21-q19
* item[19].text = "I was aware of the action of my heart in the absence of physical exertion"
* item[19].text.extension[0].url = $hl7-translation
* item[19].text.extension[0].extension[0].url = "lang"
* item[19].text.extension[0].extension[0].valueCode = #de
* item[19].text.extension[0].extension[1].url = "content"
* item[19].text.extension[0].extension[1].valueString = "Ich nahm meinen Herzschlag wahr, ohne körperlich aktiv zu sein"
* item[19].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[19].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[19].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[19].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[19].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[19].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[19].answerOption[0].extension.url = $hl7-ordinal-value
* item[19].answerOption[0].extension.valueDecimal = 0
* item[19].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[19].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[19].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[19].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[19].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[19].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[19].answerOption[1].extension.url = $hl7-ordinal-value
* item[19].answerOption[1].extension.valueDecimal = 1
* item[19].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[19].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[19].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[19].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[19].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[19].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[19].answerOption[2].extension.url = $hl7-ordinal-value
* item[19].answerOption[2].extension.valueDecimal = 2
* item[19].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[19].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[19].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[19].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[19].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[19].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[19].answerOption[3].extension.url = $hl7-ordinal-value
* item[19].answerOption[3].extension.valueDecimal = 3

// Q20 - Anxiety: I felt scared without any good reason
* item[20].linkId = "dass-dass21-q20"
* item[20].type = #choice
* item[20].prefix = "20"
* item[20].code = $mii-cs-pro-dass-21#dass-dass21-q20
* item[20].text = "I felt scared without any good reason"
* item[20].text.extension[0].url = $hl7-translation
* item[20].text.extension[0].extension[0].url = "lang"
* item[20].text.extension[0].extension[0].valueCode = #de
* item[20].text.extension[0].extension[1].url = "content"
* item[20].text.extension[0].extension[1].valueString = "Ich fürchtete mich ohne ersichtlichen Grund"
* item[20].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[20].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[20].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[20].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[20].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[20].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[20].answerOption[0].extension.url = $hl7-ordinal-value
* item[20].answerOption[0].extension.valueDecimal = 0
* item[20].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[20].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[20].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[20].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[20].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[20].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[20].answerOption[1].extension.url = $hl7-ordinal-value
* item[20].answerOption[1].extension.valueDecimal = 1
* item[20].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[20].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[20].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[20].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[20].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[20].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[20].answerOption[2].extension.url = $hl7-ordinal-value
* item[20].answerOption[2].extension.valueDecimal = 2
* item[20].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[20].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[20].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[20].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[20].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[20].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[20].answerOption[3].extension.url = $hl7-ordinal-value
* item[20].answerOption[3].extension.valueDecimal = 3

// Q21 - Depression: I felt that life was meaningless
* item[21].linkId = "dass-dass21-q21"
* item[21].type = #choice
* item[21].prefix = "21"
* item[21].code = $mii-cs-pro-dass-21#dass-dass21-q21
* item[21].text = "I felt that life was meaningless"
* item[21].text.extension[0].url = $hl7-translation
* item[21].text.extension[0].extension[0].url = "lang"
* item[21].text.extension[0].extension[0].valueCode = #de
* item[21].text.extension[0].extension[1].url = "content"
* item[21].text.extension[0].extension[1].valueString = "Ich fand das Leben sinnlos"
* item[21].answerOption[0].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[21].answerOption[0].valueCoding.display.extension[0].url = $hl7-translation
* item[21].answerOption[0].valueCoding.display.extension[0].extension[0].url = "lang"
* item[21].answerOption[0].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[21].answerOption[0].valueCoding.display.extension[0].extension[1].url = "content"
* item[21].answerOption[0].valueCoding.display.extension[0].extension[1].valueString = "Traf gar nicht auf mich zu"
* item[21].answerOption[0].extension.url = $hl7-ordinal-value
* item[21].answerOption[0].extension.valueDecimal = 0
* item[21].answerOption[1].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[21].answerOption[1].valueCoding.display.extension[0].url = $hl7-translation
* item[21].answerOption[1].valueCoding.display.extension[0].extension[0].url = "lang"
* item[21].answerOption[1].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[21].answerOption[1].valueCoding.display.extension[0].extension[1].url = "content"
* item[21].answerOption[1].valueCoding.display.extension[0].extension[1].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[21].answerOption[1].extension.url = $hl7-ordinal-value
* item[21].answerOption[1].extension.valueDecimal = 1
* item[21].answerOption[2].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[21].answerOption[2].valueCoding.display.extension[0].url = $hl7-translation
* item[21].answerOption[2].valueCoding.display.extension[0].extension[0].url = "lang"
* item[21].answerOption[2].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[21].answerOption[2].valueCoding.display.extension[0].extension[1].url = "content"
* item[21].answerOption[2].valueCoding.display.extension[0].extension[1].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[21].answerOption[2].extension.url = $hl7-ordinal-value
* item[21].answerOption[2].extension.valueDecimal = 2
* item[21].answerOption[3].valueCoding = $mii-cs-pro-dass-21#dass-dass21-answer-3 "Applied to me very much"
* item[21].answerOption[3].valueCoding.display.extension[0].url = $hl7-translation
* item[21].answerOption[3].valueCoding.display.extension[0].extension[0].url = "lang"
* item[21].answerOption[3].valueCoding.display.extension[0].extension[0].valueCode = #de
* item[21].answerOption[3].valueCoding.display.extension[0].extension[1].url = "content"
* item[21].answerOption[3].valueCoding.display.extension[0].extension[1].valueString = "Traf sehr stark auf mich zu"
* item[21].answerOption[3].extension.url = $hl7-ordinal-value
* item[21].answerOption[3].extension.valueDecimal = 3

// ============================================================================
// Score items: Raw subscale scores (DASS-21)
// ============================================================================

// Depression Raw Score (items 3, 5, 10, 13, 16, 17, 21)
* item[22].linkId = "dass-dass21-score-raw-depression"
* item[22].type = #decimal
* item[22].prefix = "Depression (Raw)"
* item[22].readOnly = true
* item[22].text = "DASS-21 Depression Raw Score"
* item[22].text.extension[0].url = $hl7-translation
* item[22].text.extension[0].extension[0].url = "lang"
* item[22].text.extension[0].extension[0].valueCode = #de
* item[22].text.extension[0].extension[1].url = "content"
* item[22].text.extension[0].extension[1].valueString = "DASS-21 Depression Rohwert"
* item[22].extension[0].url = $sdc-questionnaire-calculated-expression
* item[22].extension[0].valueExpression.name = "depressionRawScore"
* item[22].extension[0].valueExpression.language = #text/fhirpath
* item[22].extension[0].valueExpression.expression = "%depressionRaw"
* item[22].extension[1].url = $sdc-questionnaire-observation-extract
* item[22].extension[1].valueBoolean = true
* item[22].extension[2].url = $hl7-questionnaire-unit
* item[22].extension[2].valueCoding.system = $UCUM
* item[22].extension[2].valueCoding.code = #{score}
* item[22].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[22].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[22].extension[3].valueCodeableConcept.coding.code = #survey

// Anxiety Raw Score (items 2, 4, 7, 9, 15, 19, 20)
* item[23].linkId = "dass-dass21-score-raw-anxiety"
* item[23].type = #decimal
* item[23].prefix = "Anxiety (Raw)"
* item[23].readOnly = true
* item[23].text = "DASS-21 Anxiety Raw Score"
* item[23].text.extension[0].url = $hl7-translation
* item[23].text.extension[0].extension[0].url = "lang"
* item[23].text.extension[0].extension[0].valueCode = #de
* item[23].text.extension[0].extension[1].url = "content"
* item[23].text.extension[0].extension[1].valueString = "DASS-21 Angst Rohwert"
* item[23].extension[0].url = $sdc-questionnaire-calculated-expression
* item[23].extension[0].valueExpression.name = "anxietyRawScore"
* item[23].extension[0].valueExpression.language = #text/fhirpath
* item[23].extension[0].valueExpression.expression = "%anxietyRaw"
* item[23].extension[1].url = $sdc-questionnaire-observation-extract
* item[23].extension[1].valueBoolean = true
* item[23].extension[2].url = $hl7-questionnaire-unit
* item[23].extension[2].valueCoding.system = $UCUM
* item[23].extension[2].valueCoding.code = #{score}
* item[23].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[23].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[23].extension[3].valueCodeableConcept.coding.code = #survey

// Stress Raw Score (items 1, 6, 8, 11, 12, 14, 18)
* item[24].linkId = "dass-dass21-score-raw-stress"
* item[24].type = #decimal
* item[24].prefix = "Stress (Raw)"
* item[24].readOnly = true
* item[24].text = "DASS-21 Stress Raw Score"
* item[24].text.extension[0].url = $hl7-translation
* item[24].text.extension[0].extension[0].url = "lang"
* item[24].text.extension[0].extension[0].valueCode = #de
* item[24].text.extension[0].extension[1].url = "content"
* item[24].text.extension[0].extension[1].valueString = "DASS-21 Stress Rohwert"
* item[24].extension[0].url = $sdc-questionnaire-calculated-expression
* item[24].extension[0].valueExpression.name = "stressRawScore"
* item[24].extension[0].valueExpression.language = #text/fhirpath
* item[24].extension[0].valueExpression.expression = "%stressRaw"
* item[24].extension[1].url = $sdc-questionnaire-observation-extract
* item[24].extension[1].valueBoolean = true
* item[24].extension[2].url = $hl7-questionnaire-unit
* item[24].extension[2].valueCoding.system = $UCUM
* item[24].extension[2].valueCoding.code = #{score}
* item[24].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[24].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[24].extension[3].valueCodeableConcept.coding.code = #survey

// ============================================================================
// Score items: DASS-42 equivalent scores (raw * 2)
// ============================================================================

// Depression Equivalent Score
* item[25].linkId = "dass-dass21-score-equiv-depression"
* item[25].type = #decimal
* item[25].prefix = "Depression (DASS-42 equiv.)"
* item[25].readOnly = true
* item[25].text = "DASS-21 Depression Score (DASS-42 equivalent)"
* item[25].text.extension[0].url = $hl7-translation
* item[25].text.extension[0].extension[0].url = "lang"
* item[25].text.extension[0].extension[0].valueCode = #de
* item[25].text.extension[0].extension[1].url = "content"
* item[25].text.extension[0].extension[1].valueString = "DASS-21 Depression Score (DASS-42 Äquivalent)"
* item[25].extension[0].url = $sdc-questionnaire-calculated-expression
* item[25].extension[0].valueExpression.name = "depressionEquivScore"
* item[25].extension[0].valueExpression.language = #text/fhirpath
* item[25].extension[0].valueExpression.expression = "%depressionRaw * 2"
* item[25].extension[1].url = $sdc-questionnaire-observation-extract
* item[25].extension[1].valueBoolean = true
* item[25].extension[2].url = $hl7-questionnaire-unit
* item[25].extension[2].valueCoding.system = $UCUM
* item[25].extension[2].valueCoding.code = #{score}
* item[25].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[25].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[25].extension[3].valueCodeableConcept.coding.code = #survey

// Anxiety Equivalent Score
* item[26].linkId = "dass-dass21-score-equiv-anxiety"
* item[26].type = #decimal
* item[26].prefix = "Anxiety (DASS-42 equiv.)"
* item[26].readOnly = true
* item[26].text = "DASS-21 Anxiety Score (DASS-42 equivalent)"
* item[26].text.extension[0].url = $hl7-translation
* item[26].text.extension[0].extension[0].url = "lang"
* item[26].text.extension[0].extension[0].valueCode = #de
* item[26].text.extension[0].extension[1].url = "content"
* item[26].text.extension[0].extension[1].valueString = "DASS-21 Angst Score (DASS-42 Äquivalent)"
* item[26].extension[0].url = $sdc-questionnaire-calculated-expression
* item[26].extension[0].valueExpression.name = "anxietyEquivScore"
* item[26].extension[0].valueExpression.language = #text/fhirpath
* item[26].extension[0].valueExpression.expression = "%anxietyRaw * 2"
* item[26].extension[1].url = $sdc-questionnaire-observation-extract
* item[26].extension[1].valueBoolean = true
* item[26].extension[2].url = $hl7-questionnaire-unit
* item[26].extension[2].valueCoding.system = $UCUM
* item[26].extension[2].valueCoding.code = #{score}
* item[26].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[26].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[26].extension[3].valueCodeableConcept.coding.code = #survey

// Stress Equivalent Score
* item[27].linkId = "dass-dass21-score-equiv-stress"
* item[27].type = #decimal
* item[27].prefix = "Stress (DASS-42 equiv.)"
* item[27].readOnly = true
* item[27].text = "DASS-21 Stress Score (DASS-42 equivalent)"
* item[27].text.extension[0].url = $hl7-translation
* item[27].text.extension[0].extension[0].url = "lang"
* item[27].text.extension[0].extension[0].valueCode = #de
* item[27].text.extension[0].extension[1].url = "content"
* item[27].text.extension[0].extension[1].valueString = "DASS-21 Stress Score (DASS-42 Äquivalent)"
* item[27].extension[0].url = $sdc-questionnaire-calculated-expression
* item[27].extension[0].valueExpression.name = "stressEquivScore"
* item[27].extension[0].valueExpression.language = #text/fhirpath
* item[27].extension[0].valueExpression.expression = "%stressRaw * 2"
* item[27].extension[1].url = $sdc-questionnaire-observation-extract
* item[27].extension[1].valueBoolean = true
* item[27].extension[2].url = $hl7-questionnaire-unit
* item[27].extension[2].valueCoding.system = $UCUM
* item[27].extension[2].valueCoding.code = #{score}
* item[27].extension[3].url = $sdc-questionnaire-observation-extract-category
* item[27].extension[3].valueCodeableConcept.coding.system = $hl7-observation-category
* item[27].extension[3].valueCodeableConcept.coding.code = #survey
